CREATE DATABASE EVOLUTI;

USE EVOLUTI;

CREATE TABLE IF NOT EXISTS EVOLUTI.CLINICA (
    ID_CLINICA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CLINICA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_CLINICA)
);