CREATE DATABASE EVOLUTI;

USE EVOLUTI;

CREATE TABLE IF NOT EXISTS EVOLUTI.CLINICA (
    ID_CLINICA INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    CLINICA VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_CLINICA)
);

CREATE TABLE IF NOT EXISTS EVOLUTI.ENDERECO (
    ID_ENDERECO INT NOT NULL AUTO_INCREMENT,
    RUA VARCHAR(255) NOT NULL,
    NUMERO INT NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    CEP CHAR(9) NOT NULL,
    PRIMARY KEY (ID_ENDERECO)
);

CREATE TABLE IF NOT EXISTS EVOLUTI.ADMIN (
    ID_ADMIN INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    USER VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CPF CHAR(11) NOT NULL,
    RG CHAR(9) NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    FK_ENDERECO INT NOT NULL,
    FK_CLINICA INT NOT NULL,
    PRIMARY KEY (ID_ADMIN)
    FOREIGN KEY (FK_ENDERECO) REFERENCES EVOLUTI.ENDERECO(ID_ENDERECO)
    FOREIGN KEY (FK_CLINICA) REFERENCES EVOLUTI.CLINICA(ID_CLINICA)
);

CREATE TABLE IF NOT EXISTS EVOLUTI.ESTAGIARIO(
    ID_ESTAGIARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    USER VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CPF CHAR(11) NOT NULL,
    RG CHAR(9) NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    INSTITUICAO VARCHAR(255) NOT NULL,
    CONTRATO_INICIO DATE,
    CONTRATO_FIM DATE,
    FK_ENDERECO INT NOT NULL,
    FK_CLINICA INT NOT NULL,
    PRIMARY KEY (ID_ESTAGIARIO)
    FOREIGN KEY (FK_ENDERECO) REFERENCES EVOLUTI.ENDERECO(ID_ENDERECO)
    FOREIGN KEY (FK_CLINICA) REFERENCES EVOLUTI.CLINICA(ID_CLINICA)
);

CREATE TABLE IF NOT EXISTS EVOLUTI.FISIO(
    
    ID_ESTAGIARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    USER VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CPF CHAR(11) NOT NULL,
    RG CHAR(9) NOT NULL,
    GENERO VARCHAR(255) NOT NULL,
    CREFITO BIGINT,
    DATACREFITO DATE,
    ESPECIALIDADE VARCHAR(45),
    FK_ENDERECO INT NOT NULL,
    FK_CLINICA INT NOT NULL,
    PRIMARY KEY (ID_ESTAGIARIO)
    FOREIGN KEY (FK_ENDERECO) REFERENCES EVOLUTI.ENDERECO(ID_ENDERECO)
    FOREIGN KEY (FK_CLINICA) REFERENCES EVOLUTI.CLINICA(ID_CLINICA)
);